### ISSUE TITLE
Unhandled 'error' event when running gulp serve

### ISSUE THREAD

**Issue by siddhion** [krystiangw/angular-filepicker-example#1]
When I run `gulp serve` I get 

```
$ gulp serve
[18:11:18] Using gulpfile ~/dev/angular-filepicker-example/gulpfile.js
[18:11:18] Starting 'wiredep'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'main' of undefined
    at findMainFiles (/home/max/dev/angular-filepicker-example/node_modules/wiredep/lib/detect-dependencies.js:89:39)
    at /home/max/dev/angular-filepicker-example/node_modules/wiredep/lib/detect-dependencies.js:151:17
    at forOwn (/home/max/dev/angular-filepicker-example/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/home/max/dev/angular-filepicker-example/node_modules/wiredep/node_modules/lodash/dist/lodash.js:3302:9)
    at detectDependencies (/home/max/dev/angular-filepicker-example/node_modules/wiredep/lib/detect-dependencies.js:33:7)
    at wiredep (/home/max/dev/angular-filepicker-example/node_modules/wiredep/wiredep.js:65:39)
    at DestroyableTransform._transform (/home/max/dev/angular-filepicker-example/node_modules/wiredep/wiredep.js:134:34)
    at DestroyableTransform.Transform._read (/home/max/dev/angular-filepicker-example/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/max/dev/angular-filepicker-example/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/max/dev/angular-filepicker-example/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

**Comment by Hesesses** [comment]
+1

**Comment by krystiangw** [comment]
You need to run 'bower install' also. Looks like I forgot mention it in Readme file.

**Comment by krystiangw** [comment]
Solved.
